// Generated by get_unique_values
export const uniqueValuesRecipients = {
  "timeRange": [
    2000,
    2023
  ],
  "indicators": [
    "Bilateral",
    "Imputed multilateral",
    "Total"
  ],
  "donors": [
    "Australia",
    "Austria",
    "Belgium",
    "Canada",
    "Czechia",
    "DAC Countries, Total",
    "Denmark",
    "EU Institutions",
    "EU27",
    "Estonia",
    "Finland",
    "France",
    "G7 Countries, Total",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Japan",
    "Korea",
    "Lithuania",
    "Luxembourg",
    "Netherlands",
    "New Zealand",
    "Non-DAC Countries, Total",
    "Norway",
    "Official Donors, Total",
    "Poland",
    "Portugal",
    "Slovak Republic",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "United Kingdom",
    "United States"
  ],
  "recipients": [
    "Africa, Total",
    "America, Total",
    "Asia, Total",
    "Developing countries, Total",
    "Europe, Total",
    "Fragile states, Total",
    "France priority countries",
    "High income",
    "LDCs, Total",
    "LMICs, Total",
    "Low income",
    "Lower-middle income",
    "Not classified by income",
    "Oceania, Total",
    "Other LICs, Total",
    "Sahel",
    "UMICs, Total",
    "Unallocated by income",
    "Unspecified developing countries",
    "Upper-middle income"
  ],
  "currencies": [
    "British Pounds",
    "Canadian Dollars",
    "Euros",
    "US Dollars"
  ],
  "prices": [
    "Constant",
    "Current"
  ]
};
