// Generated by get_unique_values
export const uniqueValuesFinancing = {
  "timeRange": [
    2000,
    2023
  ],
  "indicators": [
    "Bilateral",
    "COVID-19 ODA, Total",
    "Core ODA",
    "Debt relief",
    "Grants",
    "In-Donor Refugee Costs",
    "In-donor imputed student costs",
    "In-donor scholarships",
    "In-donor student costs, Total",
    "Multilateral",
    "Non-grants",
    "PSI, Institutional",
    "PSI, Instrument",
    "Private sector instruments, Total",
    "Total ODA"
  ],
  "donors": [
    "Australia",
    "Austria",
    "Belgium",
    "Canada",
    "Czechia",
    "DAC Countries, Total",
    "Denmark",
    "EU Institutions",
    "EU-27",
    "EU-27 + Institutions",
    "Estonia",
    "Finland",
    "France",
    "G7 Countries, Total",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Japan",
    "Korea",
    "Lithuania",
    "Luxembourg",
    "Netherlands",
    "New Zealand",
    "Non-DAC Countries, Total",
    "Norway",
    "Poland",
    "Portugal",
    "Slovak Republic",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "United Kingdom",
    "United States"
  ],
  "currencies": [
    "British Pounds",
    "Canadian Dollars",
    "Euros",
    "US Dollars"
  ],
  "prices": [
    "Constant",
    "Current"
  ],
  "indicatorTypes": [
    "Flow",
    "Grant Equivalent",
    "Official Definition"
  ]
};
